# Copyright (c) OpenMMLab. All rights reserved.

from .templates import PROMPT_TEMPLATE, SYSTEM_TEMPLATE

from .constants import (
    BOT_TOKEN,
    EOT_TOKEN,
    BOU_TOKEN,
    EOU_TOKEN,
    BOV_TOKEN, 
    EOV_TOKEN,
    VISUAL_PROMPT_PLACEHOLDER,
    VISUAL_PROMPT_INDEX,
    VISUAL_REFERENCE_TOKEN,
    VISUAL_REPRESENTATION_TOKEN,
    SPECIAL_TOKENS
)

__all__ = [
    'PROMPT_TEMPLATE', 'SYSTEM_TEMPLATE'
    'BOT_TOKEN', 'BOT_TOKEN', 'EOT_TOKEN', 'BOU_TOKEN',
    'EOU_TOKEN', 'BOV_TOKEN', 'EOV_TOKEN',
    'VISUAL_PROMPT_PLACEHOLDER',
    'VISUAL_PROMPT_INDEX',
    'VISUAL_REFERENCE_TOKEN',
    'VISUAL_REPRESENTATION_TOKEN',
    'SPECIAL_TOKENS'
]
