# Copyright (c) OpenMMLab. All rights reserved.
from .constants import (DEFAULT_IMAGE_TOKEN, DEFAULT_PAD_TOKEN_INDEX,
                        IGNORE_INDEX, IMAGE_TOKEN_INDEX)
from .stop_criteria import StopWordStoppingCriteria
from .templates import PROMPT_TEMPLATE, SYSTEM_TEMPLATE

from .constants import (
    BOT_TOKEN,
    EOT_TOKEN,
    BOU_TOKEN,
    EOU_TOKEN,
    BOV_TOKEN, 
    EOV_TOKEN,
    VISUAL_PROMPT_PLACEHOLDER,
    VISUAL_PROMPT_INDEX,
    VISUAL_REFERENCE_TOKEN,
    VISUAL_REPRESENTATION_TOKEN,
    SPECIAL_TOKENS
)

__all__ = [
    'IGNORE_INDEX', 'DEFAULT_PAD_TOKEN_INDEX', 'PROMPT_TEMPLATE',
    'DEFAULT_IMAGE_TOKEN', 'SYSTEM_TEMPLATE', 'StopWordStoppingCriteria',
    'IMAGE_TOKEN_INDEX',
    'BOT_TOKEN', 
    'BOT_TOKEN',
    'EOT_TOKEN',
    'BOU_TOKEN',
    'EOU_TOKEN',
    'BOV_TOKEN', 
    'EOV_TOKEN',
    'VISUAL_PROMPT_PLACEHOLDER',
    'VISUAL_PROMPT_INDEX',
    'VISUAL_REFERENCE_TOKEN',
    'VISUAL_REPRESENTATION_TOKEN',
    'SPECIAL_TOKENS'
]
