# Copyright (c) OpenMMLab. All rights reserved.
IGNORE_INDEX = -100
DEFAULT_PAD_TOKEN_INDEX = 0
IMAGE_TOKEN_INDEX = -200
DEFAULT_IMAGE_TOKEN = '<image>'

# shikra constants
DEFAULT_PAD_TOKEN = "[PAD]"
DEFAULT_EOS_TOKEN = "</s>"
DEFAULT_BOS_TOKEN = "<s>"
DEFAULT_UNK_TOKEN = "<unk>"

IMAGE_PLACEHOLDER = DEFAULT_IMAGE_TOKEN
BOXES_PLACEHOLDER = '<boxes>'
EXPR_PLACEHOLDER = '<expr>'
OBJS_PLACEHOLDER = '<objs>'
QUESTION_PLACEHOLDER = '<question>'
POINTS_PLACEHOLDER = '<points>'

PHRASE_ST_PLACEHOLDER = '<ph_st>'
PHRASE_ED_PLACEHOLDER = '<ph_ed>'

MASK_PLACEHOLDER = '<masks>'
PHRASE_ST_PLACEHOLDER_STAGE2 = '<Phrase>'
PHRASE_ED_PLACEHOLDER_STAGE2 = '</Phrase>'
CLASS_PLACEHOLDER = '<cls>'

# encode
VISUAL_PROMPTS_PLACEHOLDER = '<VPT>'

# decode 
DEFAULT_BOI_TOKEN = "<i>" #TODO: MUST?
DEFAULT_EOI_TOKEN = "</i>"
VISUAL_REPRESENTATION = '<VRT>'
VISUAL_REFERENCE = '<REF>'
